### ISSUE TITLE
Při novém otevření stránky hází 500

### ISSUE THREAD

**Issue by Cactucs** [DNepovim/kraj-praha#37]
Např. při otevření v anonymním okně (nebo kdykoli když asi tam není nějaké cookie). Po reloadu funguje.

**Comment by DNepovim** [comment]
Tady je k tomu Exception page: https://praha.skauting.cz/exception--2017-09-04--20-49--d59ab19dc9.html
Napadá tě co s tím @Cactucs ?

**Comment by Cactucs** [comment]
Nepřišel jsem na to kdo spouší tedy tu session (buď někde nějak WP nebo [skautIs knihovna](https://github.com/skaut/Skautis)), ale když by se to v `theme-init` dalo do `if(session_status() !== PHP_SESSION_ACTIVE)`, tak by to mělo fungovat ;)

**Comment by DNepovim** [comment]
Tak jsem to tam vrazil a zdá se, že nic :/

**Comment by DNepovim** [comment]
Tak už to přestalo, tak snad už se to nebude dít.
Dík @Cactucs 
Kdyby ses nudil, tak je tu plno dalších issues a zatím mi jich na jedno zavřené vychází pět otevřených :)

**Comment by DNepovim** [comment]
Tak se to pořád děje, ale zjistil jsem, že se to děje i na jiném nette webu na lebedě, takže to možná bude nějaký bug u nich.
