### ISSUE TITLE
Vyřešit události

### ISSUE THREAD

**Issue by DNepovim** [DNepovim/kraj-praha#45]
Asi udělat google calendar a tahat to zněj.

**Comment by kalich5** [comment]
Dobrý plugin na zobrazování kalendáře. Dá se přes CSSko i dobře upravovat. https://cs.wordpress.org/plugins/google-calendar-events/

**Comment by DNepovim** [comment]
Zatím spíš řešíme co od "kalendáře" očekáváme a k čemu ho potřebujeme, takže by mi spíš pomohly hloubkové rozhovory s uživateli, nebo case studies...

**Comment by DNepovim** [comment]
Pak až začneme řešit implementaci. Ale děkuji za tip. Bude se hodit.

**Comment by DNepovim** [comment]
Otázky jsou asi následující:
Potřebují mít skauti v praze přehled o krajských akcích?
Jaké všechny akce by v něm měli být?
Je příjemnější mít google kalendář mezi svými kalendáři, nebo přehled na webu?
Je příjeměnší tabulkkový kalendář, nebo agenda?

**Comment by kalich5** [comment]
Takovýhle rozsah mají v Liberci https://www.skautlib.cz/terminy-a-akce/

**Comment by DNepovim** [comment]
Mě právě ve chvíli, kdy mám dvě akce v měsíci, připadá lepší udělat agendu.
