### ISSUE TITLE
"Scrollovatelné" menu na desktopu

### ISSUE THREAD

**Issue by Cactucs** [DNepovim/kraj-praha#87]
V chromu desktopu (windows) se mi zobrazuje horizontální a vertikální scrollbar (ale "disabled" - je zašedlý) kolem menu (resp. elementu `.main-nav`). Problém způsobuje pravidlo `overflow: scroll;` na zmíněném elementu - jeho odstraněním nebo nastavením na `auto` se problém řeší (ale asi je tam kvůli nějakým mobilním viewportům, tak nevím jestli tohle by zase něco nerozbilo). 

Jinak díky za jeden z nejlepších skautských webů.

**Comment by Cactucs** [comment]
V firefoxu je to stejné, přihládám printscreen: 

![image](https://user-images.githubusercontent.com/4283010/50664261-b95a3880-0fac-11e9-9ffb-24a80f174780.png)

**Comment by DNepovim** [comment]
Díky za report. Na macu se mi to neděje ani v chromu ani ve firefoxu. Na windows to teď nemám jak otestovat. Nasadil jsem tebou navrhovanou opravu. Můžeš se podívat, jestli to vyřešilo problém?

**Comment by Cactucs** [comment]
Opravilo, díky.
